### ISSUE TITLE
General Question | Custom Hotbar Functionality

### ISSUE THREAD

**Issue by webmaster94** [janssen-io/foundry-tokenhotbar-js#1]
Hello I was just reaching out to see if this module will have more functionality in the future. For example, the fact that it is not compatible with custom hotbar is unfortunate. The current version of token hotbar is and other than continued support and updating for foundry versions greater than 0.8, I don't see a reason to switch to the new version.

**Comment by janssen-io** [comment]
Hi, the old Token Hotbar had some serious issues which were hard to resolve ([#50](https://github.com/League-of-Foundry-Developers/foundry-token-hotbar/issues/50), [#46](https://github.com/League-of-Foundry-Developers/foundry-token-hotbar/issues/46) and [#38](https://github.com/League-of-Foundry-Developers/foundry-token-hotbar/issues/46)). So I created this new version that has a more stable base functionality. On top of that, the code is kept much simpler so it's easier for other developers to see what's going on (and perhaps help with maintenance later on). I hope this clarifies why this new version was necessary.

I am considering re-integrating Custom Hotbar, so if that is the only functionality you are missing then it might be worth reconsidering the update later. :) I'll create a new issue (#2) to track the progress on the integration. You can subscribe to that if you want to receive notifications about it. :)

**Comment by webmaster94** [comment]
Understood. I was not aware of these pending issues as I have not experienced them. Thank you for sating my curiosity of the revamp. While the custom hotbar integration is important to me it is not a dealbreaker. I just have no reason to switch yet as the current module is working fine for me.

**Comment by janssen-io** [comment]
I added the information about why a new package was created in the README.

#2 (integration with Custom Hotbar) is also released in [v1.2.0](https://github.com/janssen-io/foundry-tokenhotbar-js/releases/v1.2.0). So for now, I will close this issue. Feel free to comment if you have any more questions, though!
