### ISSUE TITLE
Macros on hotbar not working with Token Hotbar enabled

### ISSUE THREAD

**Issue by Weissrolf** [janssen-io/foundry-tokenhotbar-js#3]
PF2E system,

All modules disabled, except Token Hotbar:
https://i.imgur.com/z34PFBF.gif

All modules disabled, including Token Hotbar:
https://i.imgur.com/z34PFBF.gif

Using Custom Hotbar for the Token Hotbar seems to work properly, though.

Edit: corrected links to animated GIFs

**Comment by janssen-io** [comment]
Hi Weissrolf, links to the gifs are the same and I'm not sure what I'm supposed to see.
Can you give me the following information:

- Foundry Version
- System Version
- Token Hotbar version
- Macro content
- Description of what you expect to happen and what happens instead.

**Comment by Weissrolf** [comment]
Sorry, here is a new GIF, demonstrating how it should work when Token Hotbar is not enabled.
https://i.imgur.com/MxpYMga.gif

Clicking on the macro turns Barbarian Rage on the PC on/off and I can copy the macro to Custom Hotbar.

With Token Hotbar it happens that the PC effects are not updated, thus clicking the macro has no effect (see GIF in first post). When that happens then I am also not able to copy the macro to Custom Hotbar (just stays empty after dropping the macro). Unfortunately this doesn't always happen, but once it does it stays broken.

There may be a conflict with some other module, but in the first GIF I disabled all other modules. So if the conflict is with another module then it breaks so fundamentally that even disabling all modules afterwards doesn't help (I assume a relogin is necessary then).

Currently it's working, so I have to keep an eye on how to make it break again.

Foundry 0.8.9
System PF2E 2.20.2.9271 (this changed since my last post, so retesting is in order)
Token Hotbar 1.2.0
Macro content:

`const actors = canvas.tokens.controlled.flatMap((token) => token.actor ?? []);
if (!actors.length && game.user.character) {
    actors.push(game.user.character);
}
const ITEM_UUID = 'Compendium.pf2e.feature-effects.z3uyCMBddrPK5umr'; // Effect: Rage
const source = (await fromUuid(ITEM_UUID)).toObject();
source.flags.core ??= {};
source.flags.core.sourceId = ITEM_UUID;
for await (const actor of actors) {
    const existing = actor.itemTypes.effect.find((effect) => effect.getFlag('core', 'sourceId') === ITEM_UUID);
    if (existing) {
        await existing.delete();
    } else {
        await actor.createEmbeddedDocuments('Item', [source]);
    }
}`

**Comment by janssen-io** [comment]
I can't seem to reproduce this one either, rage is toggled. But I do see some errors appearing, so I think there might be another bug in token hotbar.

I'll get back to you later after I resolve that issue.

**Comment by Weissrolf** [comment]
There have been changes in the PF2E system since then, including changes rule elements (scripts). So this might have changed.

**Comment by janssen-io** [comment]
If this happens again, let me know. For now I'll close this issue.
