### ISSUE TITLE
Updating to Foundry 9.251 breaks ability to drag macros from actor to token hotbar

### ISSUE THREAD

**Issue by boloniusMonk** [janssen-io/foundry-tokenhotbar-js#9]
Updating to Foundry 9.251 breaks ability to drag macros to token hotbar.   

I have found that pulling from the Macros Directory works, but directly from the actor character sheet to the token hotbar does not.  I can drag to Norc custom hotbar when both are enabled.  Tested in dcc, ose and dnd5e.

**Comment by Cubius** [comment]
Resolved via Foundry build 9.254
see https://foundryvtt.com/releases/9.254
